// Theme: typora-purple — imported from Typora CSS
// Generated by md-to-beautiful-pdf

#let doc-title = "%%DOC_TITLE%%"
#let doc-author = "%%DOC_AUTHOR%%"
#let accent       = rgb("#8064a9")
#let text-clr     = rgb("#444444")
#let light-text   = rgb("#666666")
#let link-clr     = rgb("#2aa899")
#let code-clr     = rgb("#745fb5")
#let code-bg      = rgb("#f4f2f9")
#let block-bg     = rgb("#fdfdfd")
#let quote-border = rgb("#745fb533")
#let border-clr   = rgb("#e7e7e7")
#let table-hdr    = rgb("#fcfcfc")
#let table-even   = rgb("#fcfcfc")

#set document(title: doc-title, author: doc-author)

#set page(
  paper: "%%PAPER%%",
  margin: (top: 2.5cm, bottom: 2.5cm, left: 3cm, right: 3cm),
  header: context {
    if counter(page).get().first() > 1 {
      box(width: 1fr)[
        #set text(size: 8pt, fill: light-text)
        #h(1fr)
        #doc-title
      ]
      v(-0.5em)
      line(length: 100%, stroke: 0.5pt + accent)
    }
  },
  footer: context {
    line(length: 100%, stroke: 0.5pt + accent)
    v(-0.5em)
    set text(size: 8pt, fill: light-text)
    h(1fr)
    counter(page).display("1")
  },
)

#set text(
  font: ("Open Sans", "Clear Sans", "Helvetica Neue", "Helvetica", "Arial", "PingFang SC", "Noto Sans CJK SC", "Hiragino Sans GB"),
  size: 11pt,
  fill: text-clr,
  lang: "zh",
)

#set par(leading: 0.9em, spacing: 1.4em)

// ── Headings ──────────────────────────────────────────────────────────────────

#show heading.where(level: 1): it => {
  block(above: 2em, below: 1.2em, sticky: true)[
    #set text(size: 22pt, weight: "regular", fill: rgb("#8064a9"))
    #align(center)[
      #it.body
      #v(0.3em)
      #line(length: 5em, stroke: 2pt + rgb("#8064a9"))
    ]
  ]
}

#show heading.where(level: 2): it => {
  block(above: 1.6em, below: 0.6em, sticky: true)[
    #stack(dir: ltr, spacing: 8pt,
      rect(width: 4pt, height: 1.1em, fill: rgb("#8064a9"), radius: 1pt),
      text(size: 16pt, weight: "regular", fill: rgb("#8064a9"))[#it.body],
    )
    #v(0.05em)
    #line(length: 100%, stroke: 0.8pt + rgb("#8064a9"))
  ]
}

#show heading.where(level: 3): it => {
  block(above: 1.3em, below: 0.45em, sticky: true)[
    #set text(size: 13pt, weight: "bold", fill: accent)
    #it.body
  ]
}

#show heading.where(level: 4): it => {
  block(above: 1.1em, below: 0.4em, sticky: true)[
    #set text(size: 11pt, weight: "bold", fill: text-clr)
    #it.body
  ]
}

#show heading.where(level: 5): it => {
  block(above: 0.9em, below: 0.35em, sticky: true)[
    #set text(size: 11pt, weight: "bold", style: "italic", fill: light-text)
    #it.body
  ]
}

#show heading.where(level: 6): it => {
  block(above: 0.8em, below: 0.3em, sticky: true)[
    #set text(size: 10pt, style: "italic", fill: light-text)
    #it.body
  ]
}

// ── Code ─────────────────────────────────────────────────────────────────────

#show raw.where(block: true): it => {
  block(
    fill: block-bg,
    inset: (x: 14pt, y: 12pt),
    radius: 5pt,
    width: 100%,
    breakable: false,
    stroke: 0.5pt + border-clr,
  )[
    #set text(
      font: ("JetBrains Mono", "Cascadia Code", "Menlo", "Courier New", "Courier"),
      size: 9pt,
      fill: rgb("#3a3432"),
    )
    #it
  ]
}

#show raw.where(block: false): it => {
  box(
    fill: code-bg,
    inset: (x: 4pt, y: 2pt),
    radius: 3pt,
    baseline: 1.5pt,
    stroke: 0.3pt + quote-border,
  )[
    #set text(
      font: ("JetBrains Mono", "Cascadia Code", "Menlo", "Courier New", "Courier"),
      size: 9pt,
      fill: code-clr,
    )
    #it
  ]
}

// ── Blockquote ───────────────────────────────────────────────────────────────

#show quote.where(block: true): it => {
  block(
    inset: (left: 14pt, right: 8pt, top: 8pt, bottom: 8pt),
    stroke: (left: 3pt + quote-border),
    fill: code-bg,
    width: 100%,
    radius: (right: 3pt),
  )[
    #set text(fill: light-text, style: "italic")
    #it.body
  ]
}

// ── Table ────────────────────────────────────────────────────────────────────

#set table(
  stroke: border-clr,
  inset: (x: 9pt, y: 7pt),
  fill: (_, y) => if y == 0 { table-hdr } else if calc.odd(y) { white } else { table-even },
)
#show table.cell.where(y: 0): set text(weight: "bold")

// ── Links ────────────────────────────────────────────────────────────────────

#show link: it => {
  set text(fill: link-clr)
  underline(it)
}

// ── Figures / Images ─────────────────────────────────────────────────────────

#show figure: set block(breakable: false)
#set figure(gap: 0.7em)
#show figure.caption: set text(size: 9pt, fill: light-text, style: "italic")
#show image: it => { set image(width: 100%); it }

// ── Lists ────────────────────────────────────────────────────────────────────

#set list(indent: 1.2em, spacing: 0.5em)
#set enum(indent: 1.2em, spacing: 0.5em)

// ── TOC ──────────────────────────────────────────────────────────────────────

#show outline.entry.where(level: 1): set text(weight: "bold", fill: accent)

%%PREAMBLE%%

%%BODY%%
